- name: RedHat | Install firewalld
  package:
    name: firewalld
    state: present
  when: firewall_ports is defined

- name: RedHat | Start and enable firewalld
  service:
    name: firewalld
    state: started
    enabled: yes
  when: firewall_ports is defined

- name: RedHat | Setting firewall rules
  firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
    immediate: yes
  with_items:
    - "{{ firewall_ports | default([]) }}"