---

- name: Disable SELinux
  selinux:
    state: disabled
  when: disable_selinux

- name: Add EPEL and Docker-CE repositories
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    gpgcheck: "{{ item.gpgcheck }}"
    gpgkey: "{{ item.gpgkey }}"
  with_items:
    - name: epel
      description: EPEL YUM Repo
      baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
      gpgcheck: no
      gpgkey: ""
    - name: Docker-CE
      description: Docker-CE Repo
      baseurl: "{{ docker_yum_repo_url }}"
      gpgcheck: yes
      gpgkey: https://download.docker.com/linux/centos/gpg

- name: Manage awx user
  block:
    - name: Validate that wheel group exists
      group:
        name: "{{ awx_user_group }}"
        state: present
      when: awx_user_group is defined

    - name: Allow passwordless sudo in wheel group
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
      when: awx_user_enable_sudo

    - name: Setup user {{ awx_user }}
      user:
        name: "{{ awx_user }}"
        state: present
        group: "{{ awx_user_group }}"
        # generate_ssh_key: yes
        # ssh_key_bits: 4096
        # ssh_key_file: .ssh/id_rsa
        # ssh_key_comment: "awx"
  when: awx_user_enable

- name: Redhat | Install  dependencies.
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ awx_package_dependencies }}"
